/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.Ecran;

import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JPanel;

/**
 *
 * @author Administrateur
 */
public class EcranPrincipal extends javax.swing.JFrame implements IDrawer {

    /**
     * Creates new form EcranPrincipal
     */
    public EcranPrincipal() {
        initComponents();
        Dimension dimension = new Dimension(mapDemo.getWidth(), mapDemo.getHeight());
        JPanel slate = new Slate(dimension, this);
        mapDemo.removeAll();
        mapDemo.add(slate);
        mapDemo.revalidate();
        
        this.j2d.setVisible(false);
        this.j3d.setVisible(false);
        this.jVoisin.setVisible(false);
        this.jAutoroute.setVisible(false);
        this.jNationale.setVisible(false);
        this.jDepartementale.setVisible(false);
        this.jRestaurant.setVisible(false);
        this.jLoisir.setVisible(false);
        this.jVille.setVisible(false);

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jShowDistance = new javax.swing.JToggleButton();
        jShowTypeRoute = new javax.swing.JToggleButton();
        jShowTypeVille = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jVoisin = new javax.swing.JCheckBox();
        j2d = new javax.swing.JCheckBox();
        j3d = new javax.swing.JCheckBox();
        jDepartementale = new javax.swing.JCheckBox();
        jNationale = new javax.swing.JCheckBox();
        jAutoroute = new javax.swing.JCheckBox();
        jVille = new javax.swing.JCheckBox();
        jRestaurant = new javax.swing.JCheckBox();
        jLoisir = new javax.swing.JCheckBox();
        positionLabel = new javax.swing.JLabel();
        mapPanel = new javax.swing.JPanel();
        mapDemo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAE GRAMA");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        controlPanel.setMaximumSize(new java.awt.Dimension(350, 75));
        controlPanel.setMinimumSize(new java.awt.Dimension(350, 575));
        controlPanel.setPreferredSize(new java.awt.Dimension(350, 75));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jShowDistance.setText("Montrer distance :");
        jShowDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowDistanceActionPerformed(evt);
            }
        });
        jPanel1.add(jShowDistance);

        jShowTypeRoute.setText("Montrer routes :");
        jShowTypeRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeRouteActionPerformed(evt);
            }
        });
        jPanel1.add(jShowTypeRoute);

        jShowTypeVille.setText("Montrer villes :");
        jShowTypeVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeVilleActionPerformed(evt);
            }
        });
        jPanel1.add(jShowTypeVille);

        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 0, 7));

        jVoisin.setText("Voisins");
        jPanel2.add(jVoisin);

        j2d.setText("à 2 D");
        jPanel2.add(j2d);

        j3d.setText("à 3 D");
        jPanel2.add(j3d);

        jDepartementale.setText("D");
        jPanel2.add(jDepartementale);

        jNationale.setText("N");
        jPanel2.add(jNationale);

        jAutoroute.setText("A    ");
        jPanel2.add(jAutoroute);

        jVille.setText("V");
        jPanel2.add(jVille);

        jRestaurant.setText("R");
        jPanel2.add(jRestaurant);

        jLoisir.setText("L");
        jPanel2.add(jLoisir);

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        positionLabel.setText("X/Y");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);

        mapPanel.setMaximumSize(new java.awt.Dimension(850, 25));
        mapPanel.setMinimumSize(new java.awt.Dimension(25, 25));
        mapPanel.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(mapPanel, java.awt.BorderLayout.SOUTH);

        mapDemo.setMaximumSize(new java.awt.Dimension(500, 300));
        mapDemo.setMinimumSize(new java.awt.Dimension(500, 300));
        mapDemo.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout mapDemoLayout = new javax.swing.GroupLayout(mapDemo);
        mapDemo.setLayout(mapDemoLayout);
        mapDemoLayout.setHorizontalGroup(
            mapDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        mapDemoLayout.setVerticalGroup(
            mapDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(mapDemo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jShowDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowDistanceActionPerformed
        if (!jShowDistance.isSelected()) {
            jVoisin.setVisible(false);
            j2d.setVisible(false);
            j3d.setVisible(false);
            jVoisin.setSelected(false);
            j2d.setSelected(false);
            j3d.setSelected(false);
        } else {
            jVoisin.setVisible(true);
            j2d.setVisible(true);
            j3d.setVisible(true);
        }
    }//GEN-LAST:event_jShowDistanceActionPerformed

    private void jShowTypeRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeRouteActionPerformed
        if (!jShowTypeRoute.isSelected()) {
            jDepartementale.setVisible(false);
            jNationale.setVisible(false);
            jAutoroute.setVisible(false);
            jDepartementale.setSelected(false);
            jNationale.setSelected(false);
            jAutoroute.setSelected(false);
        } else {
            jDepartementale.setVisible(true);
            jNationale.setVisible(true);
            jAutoroute.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeRouteActionPerformed

    private void jShowTypeVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeVilleActionPerformed
        if (!jShowTypeVille.isSelected()) {
            jVille.setVisible(false);
            jRestaurant.setVisible(false);
            jLoisir.setVisible(false);
            jVille.setSelected(false);
            jRestaurant.setSelected(false);
            jLoisir.setSelected(false);
        } else {
            jVille.setVisible(true);
            jRestaurant.setVisible(true);
            jLoisir.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcranPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JCheckBox j2d;
    private javax.swing.JCheckBox j3d;
    private javax.swing.JCheckBox jAutoroute;
    private javax.swing.JCheckBox jDepartementale;
    private javax.swing.JCheckBox jLoisir;
    private javax.swing.JCheckBox jNationale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jRestaurant;
    private javax.swing.JToggleButton jShowDistance;
    private javax.swing.JToggleButton jShowTypeRoute;
    private javax.swing.JToggleButton jShowTypeVille;
    private javax.swing.JCheckBox jVille;
    private javax.swing.JCheckBox jVoisin;
    private javax.swing.JPanel mapDemo;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel positionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseAt(Point point) {
        if (point != null) {
            positionLabel.setVisible(true);
            positionLabel.setText("X:Y = " + point.x + ":" + point.y);
        } else {
            positionLabel.setVisible(false);
        }
    }
}
