/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.Ecran;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import sae.OptionsControls;
import sae.Ouverture.Input;
import sae.function.Function;

import sae.Helper;
import sae.donnees.ShowVoisins;
import sae.donnees.TLocalite;

/**
 *
 * @author Administrateur
 */
public class EcranPrincipal extends javax.swing.JFrame implements IDrawer, InformationPoint {

    public static EcranPrincipal instance;
    public final OptionsControls optionsControls = new OptionsControls();

    public final Slate slate;

    public final Function fct;

    /**
     * Creates new form EcranPrincipal
     */
    public EcranPrincipal() {
        instance = this;

        initComponents();
        Dimension dimension = new Dimension(mapDemo.getWidth(), mapDemo.getHeight());
        Input input = new Input(new File("src\\sae\\fichier\\Fichier.csv"));
        slate = new Slate(dimension, this, input.getListeLocalite(), this);
        fct = new Function();

        mapDemo.removeAll();
        mapDemo.add(slate);
        mapDemo.revalidate();

        int compteurChoix = 0;

        this.jAutoroute.setVisible(false);
        this.jNationale.setVisible(false);
        this.jDepartementale.setVisible(false);
        this.jRestaurant.setVisible(false);
        this.jLoisir.setVisible(false);
        this.jVille.setVisible(false);
        jNbrD.setVisible(false);
        jNbrN.setVisible(false);
        jNbrA.setVisible(false);
        jNbrV.setVisible(false);
        jNbrR.setVisible(false);
        jNbrL.setVisible(false);
        j2d.setEnabled(false);
        jVoisin1.setEnabled(false);
        jGastronomique.setEnabled(false);
        jCulturelle.setEnabled(false);
        jOuverte.setEnabled(false);

        String choix1 = comboVilleDepart1.getSelectedItem().toString();
        String choix2 = comboVilleDepart2.getSelectedItem().toString();
        if (!(choix1 == "Chargement...") && !(choix2 == "Chargement...")) {
            jGastronomique.setEnabled(true);
            jOuverte.setEnabled(true);
            jCulturelle.setEnabled(true);
            revalidate();
        }

        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        controlPanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jShowTypeRoute = new javax.swing.JToggleButton();
        jShowTypeVille = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jDepartementale = new javax.swing.JCheckBox();
        jNationale = new javax.swing.JCheckBox();
        jAutoroute = new javax.swing.JCheckBox();
        jVille = new javax.swing.JCheckBox();
        jRestaurant = new javax.swing.JCheckBox();
        jLoisir = new javax.swing.JCheckBox();
        PanelDistance = new javax.swing.JPanel();
        PointOrigine = new javax.swing.JLabel();
        comboVilleDepart = new javax.swing.JComboBox<>();
        jVoisin1 = new javax.swing.JCheckBox();
        j2d = new javax.swing.JCheckBox();
        jActiverFiltreD = new javax.swing.JCheckBox();
        PanelDistance1 = new javax.swing.JPanel();
        PointOrigine1 = new javax.swing.JLabel();
        comboVilleDepart1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        PointOrigine2 = new javax.swing.JLabel();
        comboVilleDepart2 = new javax.swing.JComboBox<>();
        jGastronomique = new javax.swing.JRadioButton();
        jOuverte = new javax.swing.JRadioButton();
        jCulturelle = new javax.swing.JRadioButton();
        jCompare = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jNbrD = new javax.swing.JLabel();
        jNbrN = new javax.swing.JLabel();
        jNbrA = new javax.swing.JLabel();
        jNbrV = new javax.swing.JLabel();
        jNbrR = new javax.swing.JLabel();
        jNbrL = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboVilleDepart3 = new javax.swing.JComboBox<>();
        comboVilleDepart4 = new javax.swing.JComboBox<>();
        mapPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        mapDemo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAE GRAMA");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/sae_icon.png")));
        setMinimumSize(new java.awt.Dimension(1310, 700));
        setPreferredSize(new java.awt.Dimension(1310, 700));
        setResizable(false);

        controlPanel.setMaximumSize(new java.awt.Dimension(350, 75));
        controlPanel.setMinimumSize(new java.awt.Dimension(350, 575));
        controlPanel.setPreferredSize(new java.awt.Dimension(350, 75));

        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Affichage Simple"));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jShowTypeRoute.setText("Montrer routes :");
        jShowTypeRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeRouteActionPerformed(evt);
            }
        });
        jPanel1.add(jShowTypeRoute);

        jShowTypeVille.setText("Montrer villes :");
        jShowTypeVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeVilleActionPerformed(evt);
            }
        });
        jPanel1.add(jShowTypeVille);

        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 0, 7));

        jDepartementale.setSelected(true);
        jDepartementale.setText("D");
        jDepartementale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jDepartementaleItemStateChanged(evt);
            }
        });
        jDepartementale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartementaleActionPerformed(evt);
            }
        });
        jPanel2.add(jDepartementale);

        jNationale.setSelected(true);
        jNationale.setText("N");
        jNationale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jNationaleItemStateChanged(evt);
            }
        });
        jPanel2.add(jNationale);

        jAutoroute.setSelected(true);
        jAutoroute.setText("A    ");
        jAutoroute.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jAutorouteItemStateChanged(evt);
            }
        });
        jPanel2.add(jAutoroute);

        jVille.setSelected(true);
        jVille.setText("V");
        jVille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jVilleItemStateChanged(evt);
            }
        });
        jVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVilleActionPerformed(evt);
            }
        });
        jPanel2.add(jVille);

        jRestaurant.setSelected(true);
        jRestaurant.setText("R");
        jRestaurant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRestaurantItemStateChanged(evt);
            }
        });
        jRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaurantActionPerformed(evt);
            }
        });
        jPanel2.add(jRestaurant);

        jLoisir.setSelected(true);
        jLoisir.setText("L");
        jLoisir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jLoisirItemStateChanged(evt);
            }
        });
        jPanel2.add(jLoisir);

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelDistance.setBorder(javax.swing.BorderFactory.createTitledBorder("Affichage Distance"));

        PointOrigine.setText("Choix point de d'origine :");

        comboVilleDepart.setModel(new DefaultComboBoxModel<>(new String[] { "Chargement..." }));
        comboVilleDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVilleDepartActionPerformed(evt);
            }
        });

        jVoisin1.setText("Voisins");
        jVoisin1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jVoisin1ItemStateChanged(evt);
            }
        });
        jVoisin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoisin1ActionPerformed(evt);
            }
        });

        j2d.setText("à 2 D");
        j2d.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j2dItemStateChanged(evt);
            }
        });

        jActiverFiltreD.setText("Activer ?");
        jActiverFiltreD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jActiverFiltreDItemStateChanged(evt);
            }
        });
        jActiverFiltreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActiverFiltreDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDistanceLayout = new javax.swing.GroupLayout(PanelDistance);
        PanelDistance.setLayout(PanelDistanceLayout);
        PanelDistanceLayout.setHorizontalGroup(
            PanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDistanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PointOrigine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboVilleDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(PanelDistanceLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jActiverFiltreD)
                .addGap(18, 18, 18)
                .addComponent(jVoisin1)
                .addGap(18, 18, 18)
                .addComponent(j2d, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelDistanceLayout.setVerticalGroup(
            PanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDistanceLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVilleDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PointOrigine, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoisin1)
                    .addComponent(j2d)
                    .addComponent(jActiverFiltreD))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        PanelDistance1.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparaison"));

        PointOrigine1.setText("Choix première localité :");

        comboVilleDepart1.setModel(new DefaultComboBoxModel<>(new String[] { "Chargement..." }));
        comboVilleDepart1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVilleDepart1ItemStateChanged(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 0, 7));

        PointOrigine2.setText("Choix seconde localité :");

        comboVilleDepart2.setModel(new DefaultComboBoxModel<>(new String[] { "Chargement..." }));
        comboVilleDepart2.setEnabled(false);
        comboVilleDepart2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVilleDepart2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jGastronomique);
        jGastronomique.setText("Gastronomique");
        jGastronomique.setEnabled(false);
        jGastronomique.addActionListener(this::ButtonGroup1ItemStateChanged);

        buttonGroup1.add(jOuverte);
        jOuverte.setText("Ouverte");
        jOuverte.setEnabled(false);
        jOuverte.addActionListener(this::ButtonGroup1ItemStateChanged);

        buttonGroup1.add(jCulturelle);
        jCulturelle.setText("Culturelle");
        jCulturelle.setEnabled(false);
        jCulturelle.addActionListener(this::ButtonGroup1ItemStateChanged);

        jCompare.setText("Comparer");
        jCompare.setEnabled(false);
        jCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDistance1Layout = new javax.swing.GroupLayout(PanelDistance1);
        PanelDistance1.setLayout(PanelDistance1Layout);
        PanelDistance1Layout.setHorizontalGroup(
            PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDistance1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PointOrigine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboVilleDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(PanelDistance1Layout.createSequentialGroup()
                .addGroup(PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDistance1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PointOrigine2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboVilleDepart2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDistance1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDistance1Layout.createSequentialGroup()
                                .addComponent(jGastronomique)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCulturelle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOuverte))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDistance1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jCompare)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDistance1Layout.setVerticalGroup(
            PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDistance1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PointOrigine1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVilleDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PointOrigine2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVilleDepart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PanelDistance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGastronomique)
                    .addComponent(jCulturelle)
                    .addComponent(jOuverte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCompare))
        );

        jCheckBox1.setText("Afficher Nombre");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jNbrD.setText("jLabel4");

        jNbrN.setText("jLabel5");

        jNbrA.setText("jLabel6");

        jNbrV.setText("jLabel7");

        jNbrR.setText("jLabel8");

        jNbrL.setText("jLabel9");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vérification Distance 2"));

        jLabel2.setText("Choix première localité :");

        jLabel3.setText("Choix seconde localité :");

        jLabel4.setText("En attente...");

        comboVilleDepart3.setModel(new DefaultComboBoxModel<>(new String[] { "Chargement..." }));
        comboVilleDepart3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVilleDepart3ItemStateChanged(evt);
            }
        });

        comboVilleDepart4.setModel(new DefaultComboBoxModel<>(new String[] { "Chargement..." }));
        comboVilleDepart4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVilleDepart4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboVilleDepart4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboVilleDepart3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboVilleDepart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboVilleDepart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNbrL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNbrD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNbrN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNbrV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNbrA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbrR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDistance1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNbrD)
                    .addComponent(jNbrN)
                    .addComponent(jNbrA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNbrV)
                    .addComponent(jNbrR)
                    .addComponent(jNbrL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDistance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.WEST);

        mapPanel.setMaximumSize(new java.awt.Dimension(850, 25));
        mapPanel.setMinimumSize(new java.awt.Dimension(25, 25));
        mapPanel.setPreferredSize(new java.awt.Dimension(25, 25));

        infoLabel.setVisible(false);
        infoLabel.setText("Nom");

        positionLabel.setText("X/Y");

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapPanelLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 667, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(191, 191, 191))
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapPanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(positionLabel)))
        );

        getContentPane().add(mapPanel, java.awt.BorderLayout.SOUTH);

        mapDemo.setMinimumSize(new java.awt.Dimension(960, 540));
        mapDemo.setPreferredSize(new java.awt.Dimension(960, 540));

        javax.swing.GroupLayout mapDemoLayout = new javax.swing.GroupLayout(mapDemo);
        mapDemo.setLayout(mapDemoLayout);
        mapDemoLayout.setHorizontalGroup(
            mapDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        mapDemoLayout.setVerticalGroup(
            mapDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        getContentPane().add(mapDemo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jShowTypeRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeRouteActionPerformed
        if (!jShowTypeRoute.isSelected()) {
            jDepartementale.setVisible(false);
            jNationale.setVisible(false);
            jAutoroute.setVisible(false);
        } else {
            jDepartementale.setVisible(true);
            jNationale.setVisible(true);
            jAutoroute.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeRouteActionPerformed

    private void jShowTypeVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeVilleActionPerformed
        if (!jShowTypeVille.isSelected()) {
            jVille.setVisible(false);
            jRestaurant.setVisible(false);
            jLoisir.setVisible(false);
        } else {
            jVille.setVisible(true);
            jRestaurant.setVisible(true);
            jLoisir.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeVilleActionPerformed

    private void jVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVilleActionPerformed

    }//GEN-LAST:event_jVilleActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {

            jNbrD.setVisible(true);
            jNbrN.setVisible(true);
            jNbrA.setVisible(true);
            jNbrV.setVisible(true);
            jNbrR.setVisible(true);
            jNbrL.setVisible(true);
        } else {

            jNbrD.setVisible(false);
            jNbrN.setVisible(false);
            jNbrA.setVisible(false);
            jNbrV.setVisible(false);
            jNbrR.setVisible(false);
            jNbrL.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void comboVilleDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVilleDepartActionPerformed
        String ville = comboVilleDepart.getSelectedItem().toString();
        if (ville.equals("Chargement...")) {
            return;
        }
        EcranPrincipal.instance.optionsControls.showVoisins = new ShowVoisins(Helper.getLocalite(ville));
    }//GEN-LAST:event_comboVilleDepartActionPerformed

    private void jDepartementaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartementaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepartementaleActionPerformed

    private void jRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaurantActionPerformed

    }//GEN-LAST:event_jRestaurantActionPerformed

    private void jDepartementaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jDepartementaleItemStateChanged
        EcranPrincipal.instance.optionsControls.departementales = ((evt.getStateChange() == 1));

    }//GEN-LAST:event_jDepartementaleItemStateChanged

    private void jVilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jVilleItemStateChanged
        EcranPrincipal.instance.optionsControls.villes = ((evt.getStateChange() == 1));
        EcranPrincipal.instance.comboVilleDepart.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart1.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart2.setModel(new Function(new LinkedList(slate.show)).getModel());
    }//GEN-LAST:event_jVilleItemStateChanged

    private void jRestaurantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRestaurantItemStateChanged
        EcranPrincipal.instance.optionsControls.restaurant = ((evt.getStateChange() == 1));
        EcranPrincipal.instance.comboVilleDepart.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart1.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart2.setModel(new Function(new LinkedList(slate.show)).getModel());
    }//GEN-LAST:event_jRestaurantItemStateChanged

    private void jLoisirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jLoisirItemStateChanged
        EcranPrincipal.instance.optionsControls.loisirs = ((evt.getStateChange() == 1));
        EcranPrincipal.instance.comboVilleDepart.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart1.setModel(new Function(new LinkedList(slate.show)).getModel());
        EcranPrincipal.instance.comboVilleDepart2.setModel(new Function(new LinkedList(slate.show)).getModel());
    }//GEN-LAST:event_jLoisirItemStateChanged

    private void jNationaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jNationaleItemStateChanged
        EcranPrincipal.instance.optionsControls.nationales = ((evt.getStateChange() == 1));
    }//GEN-LAST:event_jNationaleItemStateChanged

    private void jAutorouteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jAutorouteItemStateChanged
        EcranPrincipal.instance.optionsControls.autoroutes = ((evt.getStateChange() == 1));
    }//GEN-LAST:event_jAutorouteItemStateChanged

    private void jActiverFiltreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActiverFiltreDActionPerformed
        if (jActiverFiltreD.isSelected()) {
            jCheckBox1.setEnabled(false);
        } else {
            jCheckBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jActiverFiltreDActionPerformed

    private void jActiverFiltreDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jActiverFiltreDItemStateChanged

        if (jActiverFiltreD.isSelected()) {
            j2d.setEnabled(true);
            jVoisin1.setEnabled(true);
            String target = comboVilleDepart.getSelectedItem().toString();
            TLocalite localite = Helper.getLocalite(target);
            if (localite == null) {
                optionsControls.showVoisins = null;
                return;
            }
            optionsControls.showVoisins = new ShowVoisins(localite);
        } else {
            j2d.setEnabled(false);
            jVoisin1.setEnabled(false);
            j2d.setSelected(false);
            jVoisin1.setSelected(false);
            optionsControls.showVoisins = null;
        }
    }//GEN-LAST:event_jActiverFiltreDItemStateChanged

    private void jVoisin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoisin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVoisin1ActionPerformed

    private void jVoisin1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jVoisin1ItemStateChanged
        EcranPrincipal.instance.optionsControls.showVoisin1 = ((evt.getStateChange() == 1));
    }//GEN-LAST:event_jVoisin1ItemStateChanged

    private void j2dItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j2dItemStateChanged
        EcranPrincipal.instance.optionsControls.showVoisin2 = ((evt.getStateChange() == 1));
        if (j2d.isSelected()) {
            jVoisin1.setSelected(true);
            EcranPrincipal.instance.optionsControls.showVoisin1 = ((evt.getStateChange() == 1));
        } else {
            j2d.setSelected(false);
            jVoisin1.setSelected(false);
        }
    }//GEN-LAST:event_j2dItemStateChanged

    private void jCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompareActionPerformed
        Object source = Helper.getSelectedButtonText(buttonGroup1);
        String ville1 = comboVilleDepart1.getSelectedItem().toString();
        String ville2 = comboVilleDepart2.getSelectedItem().toString();
        Function fct = new Function(new LinkedList<>(slate.noeuds));
        JDialog d = new JDialog(this, "dialog Box");

        // create a label
        JLabel l = null;

        if (source == jGastronomique) {
            String res = fct._comparerGastronomie(ville1, ville2);
            if (res.equalsIgnoreCase("Egalité")) {
                l = new JLabel("Les deux villes sont autant gastronomiques", SwingConstants.CENTER);
            } else {
                l = new JLabel("La ville " + res + " est la plus gastronomique", SwingConstants.CENTER);
            }
        } else if (source == jCulturelle) {
            String res = fct._comparerCulture(ville1, ville2);
            if (res.equalsIgnoreCase("Egalité")) {
                l = new JLabel("Les deux villes sont autant culturelles", SwingConstants.CENTER);
            } else {
                l = new JLabel("La ville " + res + " est la plus culturelle", SwingConstants.CENTER);
            }
            System.out.println("C " + fct._comparerCulture(ville1, ville2));
        } else if (source == jOuverte) {
            String res = fct._comparerOuverture(ville1, ville2);
            if (res.equalsIgnoreCase("Egalité")) {
                l = new JLabel("Les deux villes sont autant ouvertes", SwingConstants.CENTER);
            } else {
                l = new JLabel("La ville " + res + " est la plus ouverte", SwingConstants.CENTER);
            }
        }

        d.add(l);
        // setsize of dialog
        d.setSize(400, 100);
        d.setLocation(getX() + (getWidth() / 2) - (400 / 2), getY() + (getHeight() / 2) - (100 / 2));
        // set visibility of dialog
        d.setVisible(true);
    }//GEN-LAST:event_jCompareActionPerformed

    private void comboVilleDepart1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVilleDepart1ItemStateChanged
        String choix = comboVilleDepart1.getSelectedItem().toString();
        if (choix.equals("Chargement...")) {
            comboVilleDepart2.setEnabled(false);
            comboVilleDepart2.setSelectedIndex(0);
            EcranPrincipal.instance.optionsControls.firstComparaison = "";
            comboVilleDepart2.setModel(new Function(new LinkedList<>(slate.show)).getModel());
        } else {
            comboVilleDepart2.setEnabled(true);
            EcranPrincipal.instance.optionsControls.firstComparaison = choix;
            comboVilleDepart2.setModel(new Function(new LinkedList<>(slate.show)).getComparaisonModel());
        }
    }//GEN-LAST:event_comboVilleDepart1ItemStateChanged

    private void comboVilleDepart2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVilleDepart2ItemStateChanged
        String choix = comboVilleDepart2.getSelectedItem().toString();
        if (choix.equals("Chargement...")) {
            jGastronomique.setEnabled(false);
            jCulturelle.setEnabled(false);
            jOuverte.setEnabled(false);
            jCompare.setEnabled(false);
            buttonGroup1.clearSelection();
        } else {
            jGastronomique.setEnabled(true);
            jCulturelle.setEnabled(true);
            jOuverte.setEnabled(true);
        }
    }//GEN-LAST:event_comboVilleDepart2ItemStateChanged

    private void comboVilleDepart3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVilleDepart3ItemStateChanged
        String choix = comboVilleDepart3.getSelectedItem().toString();
        if (choix.equals("Chargement...")) {
            jLabel4.setText("En attente...");
            comboVilleDepart4.setEnabled(false);
            comboVilleDepart4.setSelectedIndex(0);
            comboVilleDepart4.setModel(new Function(new LinkedList<>(slate.noeuds)).getModel());
        } else {
            comboVilleDepart4.setEnabled(true);
            comboVilleDepart4.setModel(new Function(new LinkedList<>(slate.noeuds)).getModel());
        }
    }//GEN-LAST:event_comboVilleDepart3ItemStateChanged

    private void comboVilleDepart4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVilleDepart4ItemStateChanged
        String choix = comboVilleDepart4.getSelectedItem().toString();
        if (choix.equals("Chargement...")) {
            jLabel4.setText("En attente...");
        } else {
            Function fct = new Function(new LinkedList<>(slate.noeuds));
            Boolean verif = fct.vérificationdistance2(comboVilleDepart3.getSelectedItem().toString(), choix);
            if (verif) {
                jLabel4.setText("Les localités sont à deux distances");
            } else {
                jLabel4.setText("Les localités ne sont pas à deux distances");
            }
        }
    }//GEN-LAST:event_comboVilleDepart4ItemStateChanged

    private void ButtonGroup1ItemStateChanged(java.awt.event.ActionEvent evt) {
        Object source = evt.getSource();
        if (source == jGastronomique || source == jCulturelle || source == jOuverte) {
            jCompare.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcranPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDistance;
    private javax.swing.JPanel PanelDistance1;
    private javax.swing.JLabel PointOrigine;
    private javax.swing.JLabel PointOrigine1;
    private javax.swing.JLabel PointOrigine2;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> comboVilleDepart;
    public javax.swing.JComboBox<String> comboVilleDepart1;
    public javax.swing.JComboBox<String> comboVilleDepart2;
    public javax.swing.JComboBox<String> comboVilleDepart3;
    public javax.swing.JComboBox<String> comboVilleDepart4;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JCheckBox j2d;
    private javax.swing.JCheckBox jActiverFiltreD;
    private javax.swing.JCheckBox jAutoroute;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JButton jCompare;
    public javax.swing.JRadioButton jCulturelle;
    private javax.swing.JCheckBox jDepartementale;
    public javax.swing.JRadioButton jGastronomique;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jLoisir;
    private javax.swing.JCheckBox jNationale;
    public javax.swing.JLabel jNbrA;
    public javax.swing.JLabel jNbrD;
    public javax.swing.JLabel jNbrL;
    public javax.swing.JLabel jNbrN;
    public javax.swing.JLabel jNbrR;
    public javax.swing.JLabel jNbrV;
    public javax.swing.JRadioButton jOuverte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox jRestaurant;
    private javax.swing.JToggleButton jShowTypeRoute;
    private javax.swing.JToggleButton jShowTypeVille;
    private javax.swing.JCheckBox jVille;
    private javax.swing.JCheckBox jVoisin1;
    private javax.swing.JPanel mapDemo;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel positionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseAt(Point point) {
        if (point != null) {
            positionLabel.setVisible(true);
            positionLabel.setText("X:Y = " + point.x + ":" + point.y);
        } else {
            positionLabel.setVisible(false);
        }
    }

    @Override
    public void infoPoint(String infoPrLabel) {
        infoLabel.setText(infoPrLabel);
    }
}
