/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.Ecran;

import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author Administrateur
 */
public class Ecran1 extends javax.swing.JFrame implements IDrawer {

    /**
     * Creates new form Ecran1
     */
    public Ecran1() {

        initComponents();
        Dimension dimension = new Dimension(mapDemo.getWidth(), mapDemo.getHeight());
        JPanel slate = new Slate(dimension, this);
        mapDemo.removeAll();
        mapDemo.add(slate);
        mapDemo.revalidate();
        this.j2d.setVisible(false);
        this.j3d.setVisible(false);
        this.jVoisin.setVisible(false);
        this.jCheckBox4.setVisible(false);
        this.jCheckBox5.setVisible(false);
        this.jCheckBox6.setVisible(false);
        this.jCheckBox7.setVisible(false);
        this.jCheckBox8.setVisible(false);
        this.jCheckBox9.setVisible(false);

        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        positionLabel = new javax.swing.JLabel();
        jShowDistance = new javax.swing.JToggleButton();
        jShowTypeRoute = new javax.swing.JToggleButton();
        jShowTypeVille = new javax.swing.JToggleButton();
        jVoisin = new javax.swing.JCheckBox();
        j2d = new javax.swing.JCheckBox();
        j3d = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mapPanel = new javax.swing.JPanel();
        mapDemo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.BorderLayout());

        positionLabel.setText("X/Y");

        jShowDistance.setText("Montrer distance");
        jShowDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowDistanceActionPerformed(evt);
            }
        });

        jShowTypeRoute.setText("Montrer routes");
        jShowTypeRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeRouteActionPerformed(evt);
            }
        });

        jShowTypeVille.setText("Montrer villes");
        jShowTypeVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTypeVilleActionPerformed(evt);
            }
        });

        jVoisin.setText("Voisins");

        j2d.setText("2 d");

        j3d.setText("3 d");

        jCheckBox4.setText("N");

        jCheckBox5.setText("D");

        jCheckBox6.setText("A");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("V");

        jCheckBox8.setText("R");

        jCheckBox9.setText("L");

        jLabel1.setText(":");

        jLabel2.setText(":");

        jLabel3.setText(":");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionLabel)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jShowTypeVille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jShowTypeRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jShowDistance, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(4, 4, 4)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox6))
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox9))
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jVoisin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j2d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j3d)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShowDistance)
                    .addComponent(jVoisin)
                    .addComponent(j2d)
                    .addComponent(j3d)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShowTypeRoute)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShowTypeVille)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(positionLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);
        getContentPane().add(mapPanel, java.awt.BorderLayout.SOUTH);

        mapDemo.setBackground(new java.awt.Color(78, 92, 120));
        mapDemo.setAlignmentX(0.0F);
        mapDemo.setAlignmentY(0.0F);
        mapDemo.setMaximumSize(new java.awt.Dimension(1000, 1000));
        mapDemo.setMinimumSize(new java.awt.Dimension(550, 350));
        mapDemo.setPreferredSize(new java.awt.Dimension(550, 350));
        mapDemo.setLayout(new java.awt.FlowLayout(0, 0, 0));
        getContentPane().add(mapDemo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jShowDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowDistanceActionPerformed
        if (!jShowDistance.isSelected()) {
            jVoisin.setVisible(false);
            j2d.setVisible(false);
            j3d.setVisible(false);
        } else {
            jVoisin.setVisible(true);
            j2d.setVisible(true);
            j3d.setVisible(true);
        }
    }//GEN-LAST:event_jShowDistanceActionPerformed

    private void jShowTypeRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeRouteActionPerformed
        if (!jShowTypeRoute.isSelected()) {
            jCheckBox4.setVisible(false);
            jCheckBox5.setVisible(false);
            jCheckBox6.setVisible(false);
        } else {
            jCheckBox4.setVisible(true);
            jCheckBox5.setVisible(true);
            jCheckBox6.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeRouteActionPerformed

    private void jShowTypeVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTypeVilleActionPerformed
        if (!jShowTypeRoute.isSelected()) {
            jCheckBox7.setVisible(false);
            jCheckBox8.setVisible(false);
            jCheckBox9.setVisible(false);
        } else {
            jCheckBox7.setVisible(true);
            jCheckBox8.setVisible(true);
            jCheckBox9.setVisible(true);
        }
    }//GEN-LAST:event_jShowTypeVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ecran1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ecran1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ecran1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ecran1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ecran1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JCheckBox j2d;
    private javax.swing.JCheckBox j3d;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jShowDistance;
    private javax.swing.JToggleButton jShowTypeRoute;
    private javax.swing.JToggleButton jShowTypeVille;
    private javax.swing.JCheckBox jVoisin;
    private javax.swing.JPanel mapDemo;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel positionLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Lorsque la souris se déplace sur le {@link Slate}
     *
     * @param point Correspond à la nouvelle position de la souris
     */
    @Override
    public void mouseAt(Point point) {
        if (point != null) {
            positionLabel.setVisible(true);
            positionLabel.setText("X:Y = " + point.x + ":" + point.y);
        } else {
            positionLabel.setVisible(false);
        }
    }
}
