/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.Ecran;

/**
 *
 * @author Administrateur
 */
public class Splash_Form extends javax.swing.JFrame {

    /**
     * Creates new form Splash_Form
     */
    public Splash_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLoadLabel = new javax.swing.JLabel();
        jPercent = new javax.swing.JLabel();
        jProgressBarLoad = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 275));
        setMinimumSize(new java.awt.Dimension(500, 275));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setLayout(null);

        jLoadLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLoadLabel.setForeground(new java.awt.Color(204, 204, 204));
        jLoadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoadLabel.setText("Chargement...");
        jPanel1.add(jLoadLabel);
        jLoadLabel.setBounds(0, 60, 500, 32);

        jPercent.setForeground(new java.awt.Color(204, 204, 204));
        jPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jPercent);
        jPercent.setBounds(0, 120, 500, 30);

        jProgressBarLoad.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jProgressBarLoad);
        jProgressBarLoad.setBounds(100, 180, 300, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLoadLabel;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jPercent;
    public javax.swing.JProgressBar jProgressBarLoad;
    // End of variables declaration//GEN-END:variables
}
